package unisabana.edu.plataformaTutorias.Reservas;

public enum MateriasEnum {
    PROGRAMACION, CALCULO , FISICA, EPIDEMIOLOGIA, ANATOMIA, OPERACIONES, ESCRITURA, FOTOGRAFIA, HISTORIA,
    LEYES, JUICIO, JURISDICCION, APREDIZAJE, DIDACTICA, PEDAGOGIA
}
